name: Selenium Tests CI/CD

on:
  push:
    branches: ["main", "develop"]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  checks: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Run Selenium Tests
        run: mvn clean test
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
          if-no-files-found: ignore

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
          retention-days: 7
          if-no-files-found: ignore

      - name: Publish Test Report (Dorny)
        if: always()
        uses: dorny/test-reporter@v1
        continue-on-error: true
        with:
          name: Test Results
          path: "target/surefire-reports/*.xml"
          reporter: "java-junit"
          fail-on-error: false

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          gh_pages: gh-pages-dir
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
